function Im2PC(img_depth, img_color, img_alpha, topleft, outname)

%% load
nrcs = size(img_depth);
sz = [nrcs, nrcs(1) * nrcs(2)];
sz(end) = sum(sum(img_alpha));

% RGB-D camera constants
center = [320 240];
[imh, imw] = size(img_depth);
constant = 570.3;
MM_PER_M = 1000;

% convert depth image to 3d point clouds
xgrid = ones(imh,1)*(1:imw) + (topleft(1)-1) - center(1);
ygrid = (1:imh)'*ones(1,imw) + (topleft(2)-1) - center(2);
X = xgrid.*img_depth/constant/MM_PER_M;
Y = ygrid.*img_depth/constant/MM_PER_M;
Z = img_depth/MM_PER_M;
X = X(img_alpha); Y = Y(img_alpha); Z = Z(img_alpha);

%% color
image_pick = zeros(sz(end), 3, 'uint8');
for i = 1:3
    cc = img_color(:, :, i);
    image_pick(:, i) = cc(img_alpha);
end

%% export
export_ply(outname, sz, X, Y, Z, image_pick);

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function export_ply(outname, sz, X, Y, Z, image_data)
% dump ply format data

fid = fopen(outname, 'w');
% header
fprintf(fid, 'ply\n');
fprintf(fid, 'format ascii 1.0\n');
fprintf(fid, 'comment generated by depth2pointcloud\n');
fprintf(fid, 'element vertex %d\n', sz(end));
fprintf(fid, 'property float x\n');
fprintf(fid, 'property float y\n');
fprintf(fid, 'property float z\n');
fprintf(fid, 'property uchar red\n');
fprintf(fid, 'property uchar green\n');
fprintf(fid, 'property uchar blue\n');
fprintf(fid, 'end_header\n');
% data
for k = 1:sz(end)
    fprintf(fid, '%f %f %f %u %u %u\n', X(k), Y(k), Z(k), ...
        image_data(k, 1), image_data(k, 2), image_data(k, 3));
end
fclose(fid);

end
